### ISSUE TITLE
Valve control issue

### ISSUE THREAD

**Issue by jsavagebtx** [CETONI-Software/cetoni-sdk-for-python#1]
Hey there,

We're having some issues controlling our two, 3 position ball valves connected to our Nemesys high pressure modules.

We're able to make them move into two positions out of three. They switch into position 3 briefly, before switching back to one of the other previous positions. Other times, position 1 will exhibit the same behaviour. When these errors occur, both valves behave the same. Querying the state of the valves shows that it thinks it's in the right position, regardless of what the valve is doing in real life.

We're doing:

import qmixsdk
from qmixsdk import qmixbus
from qmixsdk import qmixpump
from qmixsdk import qmixvalve

bus = qmixbus.Bus()
bus.open("C:/Users/Public/Documents/QmixElements/Projects/default_project/Configurations/CONF1", "")
bus.start()

valve = qmixvalve.Valve()
valve.lookup_by_device_index(0)
valve.switch_valve_to_position(0) # Works
valve.switch_valve_to_position(1) # Works
valve.switch_valve_to_position(2) # Works, before switching back to a different position

Any insight you could give us would be greatly appreciated.

**Comment by githubuser0xFFFF** [comment]
Please send your support request with your zipped device configuration or the with the complete exported project from CETONI Elements to info@cetoni.de and also add information about your SDK version.
